#!/bin/bash

set -e

. "$(dirname "$0")/../config"

case "$DEVURL" in
http://*|https://*|ftp://*)
	arg=()
	for loc in "$@"
	do
		arg+=("${DEVURL}${loc}")
	done
	if [[ "$DEVURL" =~ ://.*@ ]]; then
		wget -N --ask-password "${arg[@]}"
	else
		wget -N "${arg[@]}"
	fi
	;;
file://*)
	for loc in "$@"
	do
		src="${DEVURL#file://}$loc" 
		if ! [ -e "$src" ]; then
			echo "$src does not exist" >&2
			exit 1
		fi
		if ! [ -e "$(basename "$src")" ] || [ "$(($(stat -f'%m' "$src") > $(stat -f'%m' $(basename "$src"))))" = 1 ]; then
			cp "$src" .
		fi
	done
esac

