#!/bin/bash

set -e

. "$(dirname "$0")/../config"

siteroot="$(dirname "$0")/../siteroot"
siteref="$siteroot/$SITENAME"
general_rsync_filter="$(dirname "$0")/general-rsync-filter"
PURPOSE=${PURPOSE:deployment}

mkdir -p siteroot

for modules in "$@"; do
    if [ -e "$modules/Makefile" ]; then
        make -C "$modules" "$PURPOSE"
    fi
    for part in doc prog var; do
        pdir="$modules/site.$part"
        if [ -e "$pdir" ]; then
            if [ -e "$pdir/rsync-filter" ]; then
                rsync -tlr -f ". $pdir/rsync-filter" \
                    -f ". $general_rsync_filter" \
                    "$pdir/" "${siteref}.${part}/"
            else
                rsync -tlr \
                    -f ". $general_rsync_filter" \
                    "$pdir/" "${siteref}.${part}/"
            fi
        fi
    done
done

# vim: ts=4 sw=4 ai et
